## Last Updated 11/01/2025
namespace: f5networks
name: f5_infra_as_code_deployments
version: 1.0.0
readme: README.md
authors:
  - mmabis@f5.com
description: Automated Deployments of F5 Products using Infra As Code with Ansible Automation Platform
license_file: LICENSE
tags:
  - infrastructure
  - iac
  - cloud
  - tools
dependencies:
  f5networks.f5_modules: '*'
  f5networks.f5_bigip: '*'
  f5networks.f5os: '*'
  ansible.utils: '*'
  ansible.posix: '*'
  ansible.netcommon: '*'
  ansible.controller: '*'
  ansible.platform: '*'
  amazon.aws: '*'
  amazon.cloud: '*'
  awx.awx: '*'
  azure.azcollection: '*'
  cloud.terraform: '*'
  community.aws: '*'
  community.azure: '*'
  community.docker: '*'
  community.general: '*'
  community.kubernetes: '*'
  community.proxmox: '*'
  community.vmware: '*'
  containers.podman: '*'
  google.cloud: '*'
  redhat.openshift: '*'
  
repository: https://github.com/f5devcentral/f5-bd-ansible-infra-as-code
documentation: https://github.com/f5devcentral/f5-bd-ansible-infra-as-code
homepage: https://github.com/f5devcentral/f5-bd-ansible-infra-as-code
issues: https://github.com/f5devcentral/f5-bd-ansible-infra-as-code/issues
build_ignore:
  - ".venv"
  - "venv"
