---
# Encrypt this file with: ansible-vault encrypt group_vars/vault.yml
# Reference in AAP as a Vault credential type

vault_cifs_username: "svc-ansible"
vault_cifs_password: "CHANGEME"
vault_f5_admin_password: "CHANGEME"
vault_f5_root_password: "CHANGEME"
vault_f5_license_key_node1: "XXXXX-XXXXX-XXXXX-XXXXX-XXXXXXX"
vault_f5_license_key_node2: "XXXXX-XXXXX-XXXXX-XXXXX-XXXXXXX"
bastion_ssh_key: "/var/lib/awx/.ssh/bastion_id_rsa"
